// BookingApp/CsvMappings/InventoryItemMap.cs
using BookingApp.Models;
using CsvHelper.Configuration;
using System.Globalization;

namespace BookingApp.CsvMappings
{
    public sealed class InventoryItemMap : ClassMap<InventoryItem>
    {
        public InventoryItemMap()
        {
            // Map CSV columns to InventoryItem properties
            // The Id column is auto-generated by the database, so we don't map it from CSV.
            Map(i => i.Title).Name("title");
            Map(i => i.Description).Name("description");
            Map(i => i.RemainingCount).Name("remaining_count");
            // For expiration_date, the format is "dd/MM/yyyy"
            Map(i => i.ExpirationDate).Name("expiration_date").TypeConverterOption.Format("dd/MM/yyyy");
        }
    }
}