// BookingApp/CsvMappings/MemberMap.cs
using BookingApp.Models;
using CsvHelper.Configuration;
using System.Globalization;

namespace BookingApp.CsvMappings
{
    public sealed class MemberMap : ClassMap<Member>
    {
        public MemberMap()
        {
            // Map CSV columns to Member properties
            // The Id column is auto-generated by the database, so we don't map it from CSV.
            Map(m => m.Name).Name("name");
            Map(m => m.Surname).Name("surname");
            Map(m => m.BookingCount).Name("booking_count");
            // For date_joined, specify the format if it's not the default
            Map(m => m.DateJoined).Name("date_joined").TypeConverterOption.Format("yyyy-MM-ddTHH:mm:ss");
        }
    }
}